### ISSUE TITLE
Create 3-step guide content

### ISSUE THREAD

**Issue by jgwalker** [bit-broker/examples#9]
Create 3-step* guide content, which gives instructions on how to deploy BBK along with examples connector(s) and apps, and included a deeper-dive which explains what is happening in each step.

\* - 3 steps:

1. Deploy BBK core
2. Configure and deploy examples connector(s), apps, users, policies & keys
3. Explore data in the context of policy through the apps

**Comment by pete-rai** [comment]
This is now part of the site documentation
